mycar:
  name: axd
  price: 123
spring:
  servlet:
    multipart:
      max-request-size: 500MB
      max-file-size: 60MB


management:
  endpoints:
    enabled-by-default: true #暴露所有端点信息
    web:
      exposure:
        include: '*'  #以web方式暴露
  endpoint:
    beans:
      enabled: false  #手动关闭endpoint
